project:
  type: website
  output-dir: docs

website:
  title: "ShuyuanZheng"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ShuyuanResume.pdf
        text: Resume


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



